=== Rubenvalleho/LMSG-DAM1-RubenVallejo/Tema6/Ejercicio5/proyecto.dtd
<!ELEMENT Proyecto (Nombre,Tareas,Usuarios)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Tareas (Tarea+)>
<!ATTLIST Tarea id ID #REQUIRED>
<!ELEMENT Tarea (Titulo,Responsable)>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Responsable (IDPersona)>
<!ELEMENT IDPersona (#PCDATA)>
<!ELEMENT Usuarios (Usuario+)>
<!ATTLIST Usuario id ID #REQUIRED>
<!ATTLIST Usuario rol CDATA #REQUIRED>
<!ELEMENT Usuario (NombreUsuario)>
<!ELEMENT NombreUsuario (#PCDATA)>

=== Rubenvalleho/LMSG-DAM1-RubenVallejo/Tema6/Ejercicio5/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Proyecto SYSTEM "proyecto.dtd">
<Proyecto>
  <Nombre>Proyecto A</Nombre>
  <Tareas>
    <Tarea id="T1">
      <Titulo>Desarrollar aplicación</Titulo>
      <Responsable>
        <IDPersona>U1</IDPersona>
      </Responsable>
    </Tarea>
    <Tarea id="T2">
      <Titulo>Probar aplicación</Titulo>
      <Responsable>
        <IDPersona>U2</IDPersona>
      </Responsable>
    </Tarea>
  </Tareas>
  <Usuarios>
    <Usuario id="U1" rol="desarrollador">
      <NombreUsuario>Juan Pérez</NombreUsuario>
    </Usuario>
    <Usuario id="U2" rol="tester">
      <NombreUsuario>María González</NombreUsuario>
    </Usuario>
  </Usuarios>
</Proyecto>
