=== Rubenvalleho/LMSG-DAM1-RubenVallejo/Tema5/XML/Ejercicio2/coches.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="coches">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"/>
                            <xs:element name="modelo" type="xs:string"/>
                            <xs:element name="aÃ±o" type="xs:string"/>
                            <xs:element name="precio" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Rubenvalleho/LMSG-DAM1-RubenVallejo/Tema5/XML/Ejercicio2/coches.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="coches.xslt" type="text/xsl"?>
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="coches.xsd">
    <coche>
        <marca>Dacia</marca>
        <modelo>Sandero</modelo>
        <año>2023</año>
        <precio>16.000€</precio>
    </coche>
    <coche>
        <marca>Mazda</marca>
        <modelo>3</modelo>
        <año>2023</año>
        <precio>25.000€</precio>
    </coche>
</coches>
