=== Rubenvalleho/LMSG-DAM1-RubenVallejo/Tema6/Ejercicio3/lista_de_tareas.dtd
<!ELEMENT ListaDeTareas (Tarea+)>
<!ELEMENT Tarea (Titulo, Subtareas)>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Subtareas (Subtarea+)>
<!ELEMENT Subtarea (#PCDATA)>

=== Rubenvalleho/LMSG-DAM1-RubenVallejo/Tema6/Ejercicio3/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ListaDeTareas SYSTEM "lista_de_tareas.dtd">
<ListaDeTareas>
  <Tarea>
    <Titulo>Preparar la presentación</Titulo>
    <Subtareas>
      <Subtarea>Crear diapositivas</Subtarea>
      <Subtarea>Ensayar presentación</Subtarea>
    </Subtareas>
  </Tarea>
  <Tarea>
    <Titulo>Organizar el evento</Titulo>
    <Subtareas>
      <Subtarea>Reservar lugar</Subtarea>
      <Subtarea>Contratar servicios de catering</Subtarea>
    </Subtareas>
  </Tarea>
  <Tarea>
    <Titulo>Comprar regalos</Titulo>
    <Subtareas>
      <Subtarea>Seleccionar tiendas</Subtarea>
    </Subtareas>
  </Tarea>
</ListaDeTareas>
