=== Rubenvalleho/LMSG-DAM1-RubenVallejo/Tema5/XML/Ejercicio1/empleados.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definicion del elemento empleados-->
    <xs:element name="empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Definicion del elemento nombre-->
                            <xs:element name="nombre" type="xs:string"/>

                            <!-- Definicion del elemento apellido-->
                            <xs:element name="apellido" type="xs:string"/>

                            <!-- Definicion del elemento puesto-->
                            <xs:element name="puesto" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Rubenvalleho/LMSG-DAM1-RubenVallejo/Tema5/XML/Ejercicio1/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="empleados.xslt" type="text/xsl"?>
<empleados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="empleados.xsd">
    <empleado>
        <nombre>Juan</nombre>
        <apellido>Pérez</apellido>
        <puesto>Desarrollador</puesto>
    </empleado>
    <empleado>
        <nombre>María</nombre>
        <apellido>Gómez</apellido>
        <puesto>Diseñadora</puesto>
    </empleado>
    <empleado>
        <nombre>Rubén</nombre>
        <apellido>Vallejo</apellido>
        <puesto>Desarrollador</puesto>
    </empleado>
</empleados>
